---
driver:
  name: vagrant

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: chef_zero
  client_rb:
    chef_license: accept

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

verifier:
  name: inspec
  format: html

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-19.04
  # - name: centos-5
  # - name: centos-6
  - name: centos-7
  - name: centos-8
  # - name: windows-2012
  #   driver:
  #     box: mwrock/Windows2012R2
  # - name: windows-2016
  #   driver:
  #     box: mwrock/Windows2016

suites:
  - name: default
    run_list:
      - recipe[example-hardening::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
